#!/bin/sh

# find out which distribution we are running on
LFILE="/etc/os-release"
MFILE="/System/Library/CoreServices/SystemVersion.plist"
if [[ -f $LFILE ]]; then
	_distro=$(awk '/^ID=/' /etc/*-release | awk -F'=' '{ print tolower($2) }' | tr -d '"')
	echo "$_distro"
elif [[ -f $MFILE ]]; then
	_distro="macos"
	echo "$_distro"
else
	echo "Unsupported distribution"
fi
