#!/usr/bin/env bash

######################################################################
#             Select multiple files in fzf and trash it              #
######################################################################
results=$(fzf -m --border-label="╣ Trash multiple files ╠" --header="Tab to select, Ctrl-C to cancel" | tr '\n' ' ')
echo "trash ${results::-1}"
eval "trash $results"
