#!/usr/bin/env bash

######################################################################
#               Pipe `tmux ls` to fzf to kill session                #
######################################################################
fzf_tks=$(
    tmux ls | awk '{print $1}' | rg ':' -r '' | fzf -m \
        --border-label="╣ Tmux Kill ╠" \
        --header="Tab to select, Ctrl-C to cancel"
)
for s in $fzf_tks; do
    tmux kill-session -t "$s"
done
