[global]
allow_overwrite = true
renderable = false     # globally disables templating

[context]
btop.theme = "\"/home/charles/.config/btop/themes/catppuccin_mocha.theme\""
logseq.dark_theme = "\"assets:///home/charles/.logseq/plugins/logseq-catppuccin/ctp-macchiato.css\""
logseq.light_theme = "\"assets:///home/charles/.logseq/plugins/logseq-catppuccin/ctp-latte.css\""
wezterm.window_decorations = "\"INTEGRATED_BUTTONS | RESIZE\""
wget.hst = "/home/charles/.cache/wget-hsts"
zsh.xdg_runtime_dir = "/run/user/$UID"
zsh.homebrew_path = ""
zsh.pnpm_path = "$XDG_DATA_HOME/pnpm"

#--------------------------------------------------------------------#
#                             core-utils                             #
#--------------------------------------------------------------------#

# [[local]]
# name = "bash"
# base = "~/dotfiles/core-utils/bash"
# sources = [".bash/", ".bashrc", ".local/"]
# target = "~"

[[local]]
name = "zsh"
base = "~/dotfiles/core-utils/zsh/zsh"
sources = [".zshrc", "aliasrc", "completion/", "*.zsh"]
target = "~/.config/zsh"
method = "Copy"

[[local]]
name = "zshenv"
base = "~/dotfiles/core-utils/zsh"
sources = [".zshenv"]
target = "~"
method = "Copy"
renderable = true

[[local]]
name = "shelden"
base = "~/dotfiles/core-utils/shelden"
sources = ["plugins.toml"]
target = "~/.config/sheldon"

[[local]]
name = "git"
base = "~/dotfiles/core-utils/git"
sources = ["config"]
target = "~/.config/git"

# [[local]]
# name = "ssh"
# base = "~/dotfiles/core-utils/ssh"
# sources = ["config"]
# target = "~/.ssh"
# method = "Copy"

#--------------------------------------------------------------------#
#                              lang-vms                              #
#--------------------------------------------------------------------#

# [[local]]
# name = "asdf-vm"
# base = "~/dotfiles/lang-vms/asdf"
# sources = [".tool-versions"]
# target = "~"

[[local]]
name = "rtx-vm"
base = "~/dotfiles/lang-vms/rtx"
sources = ["config.toml"]
target = "~/.config/rtx"

#--------------------------------------------------------------------#
#                             cli-utils                              #
#--------------------------------------------------------------------#

[[local]]
name = "bat"
base = "~/dotfiles/cli-utils/bat"
sources = ["config", "themes/"]
target = "~/.config/bat"

# [[local]]
# name = "bottom"
# base = "~/dotfiles/cli-utils/bottom"
# sources = ["bottom.toml"]
# target = "~/.config/bottom"

[[local]]
name = "btop"
base = "~/dotfiles/cli-utils/btop"
sources = ["btop.conf", "themes/"]
target = "~/.config/btop"
renderable = true

[[local]]
name = "dt-cli"
base = "~/dotfiles/cli-utils/dt"
sources = ["*.toml"]
target = "~/.config/dt"

[[local]]
name = "fd"
base = "~/dotfiles/cli-utils/fd"
sources = ["ignore"]
target = "~/.config/fd"

# [[local]]
# name = "gitui"
# base = "~/dotfiles/cli-utils/gitui"
# sources = ["theme.ron"]
# target = "~/.config/gitui"

[[local]]
name = "glow"
base = "~/dotfiles/cli-utils/glow"
sources = ["glow.yml"]
target = "~/.config/glow"

# [[local]]
# name = "htop"
# base = "~/dotfiles/cli-utils/htop"
# sources = ["htoprc"]
# target = "~/.config/htop"

[[local]]
name = "joshuto"
base = "~/dotfiles/cli-utils/joshuto"
sources = ["*.toml"]
target = "~/.config/joshuto"

[[local]]
name = "lazygit"
base = "~/dotfiles/cli-utils/lazygit"
sources = ["config.yml"]
target = "~/.config/lazygit"

# [[local]]
# name = "lf"
# base = "~/dotfiles/cli-utils/lf"
# sources = ["lfrc", "git-prompt.sh", "icon.sh"]
# target = "~/.config/lf"

[[local]]
name = "lsd"
base = "~/dotfiles/cli-utils/lsd"
sources = ["config.yaml"]
target = "~/.config/lsd"

[[local]]
name = "Manual"                      #man
base = "~/dotfiles/cli-utils/Manual"
sources = ["*.1", "fzf/", "zoxide/"]
target = "~/.local/share/man/man1"

# [[local]]
# name = "navi"
# base = "~/dotfiles/cli-utils/navi"
# sources = ["config.yaml"]
# target = "~/.config/navi"

# [[local]]
# name = "neofetch"
# base = "~/dotfiles/cli-utils/neofetch"
# sources = ["config.conf"]
# target = "~/.config/neofetch"

[[local]]
name = "pistol"
base = "~/dotfiles/cli-utils/pistol"
sources = ["pistol.conf"]
target = "~/.config/pistol"

[[local]]
name = "starship"
base = "~/dotfiles/cli-utils/starship"
sources = ["starship.toml"]
target = "~/.config/starship"

# [[local]]
# name = "tmux"
# base = "~/dotfiles/cli-utils/tmux"
# sources = ["tmux.conf"]
# target = "~/.config/tmux"

[[local]]
name = "topgrade"
base = "~/dotfiles/cli-utils/topgrade.d"
sources = ["topgrade.toml"]
target = "~/.config/topgrade.d"

[[local]]
name = "Usercommand"                      # scripts
base = "~/dotfiles/cli-utils/Usercommand"
sources = ["./*"]
target = "~/.local/bin"

[[local]]
name = "wget"
base = "~/dotfiles/cli-utils/wget"
sources = ["wgetrc"]
target = "~/.config/wget"
renderable = true

[[local]]
name = "yarn"
base = "~/dotfiles/cli-utils/yarn"
sources = ["config"]
target = "~/.config/yarn"

#--------------------------------------------------------------------#
#                             gui-utils                              #
#--------------------------------------------------------------------#
[[local]]
name = "Fonts"
base = "~/dotfiles/gui-utils/Fonts"
sources = ["./*"]
target = "~/.local/share/fonts"

[[local]]
name = "gtk4"
base = "~/dotfiles/gui-utils/gtk/Catppuccin-Macchiato-Standard-Teal-dark/gtk-4.0"
sources = ["assets/", "*.css"]
target = "~/.config/gtk-4.0"

[[local]]
name = "gtk"
base = "~/dotfiles/gui-utils/gtk/Catppuccin-Macchiato-Standard-Teal-dark"
sources = ["gtk-2.0/", "gtk-3.0/", "index.theme"]
target = "~/.themes"

[[local]]
name = "gnome-shell-theme"
base = "~/dotfiles/gui-utils/gtk/Catppuccin-Macchiato-Standard-Teal-dark/gnome-shell"
sources = ["assets/", "*.css", "*.svg"]
target = "~/.themes/gnome-shell"

[[local]]
name = "logseq"
base = "~/dotfiles/gui-utils/logseq"
sources = ["config/*.edn", "settings/*.json", "preferences.json"]
target = "~/.logseq"
renderable = true

#--------------------------------------------------------------------#
#                             terminals                              #
#--------------------------------------------------------------------#

[[local]]
name = "wezterm"
base = "~/dotfiles/terminals/wezterm"
sources = ["config/", "*.lua"]
target = "~/.config/wezterm"
renderable = true

#--------------------------------------------------------------------#
#                              wm-utils                              #
#--------------------------------------------------------------------#

#NOTE: will have permissions issue, copy it manually
# [[local]]
# name = "logiops"
# base = "~/dotfiles/wm-utils/logiops"
# sources = ["logid.cfg"]
# target = "/etc"
# method = "Copy"

# [[local]]
# name = "rofi"
# base = "~/dotfiles/wm-utils/rofi"
# sources = ["config.rasi", "scripts/", "themes/"]
# target = "~/.config/rofi"
