#!/usr/bin/env bash

##
## ## Gruvbox
## * https://github.com/morhetz/gruvbox
##

xsetroot -solid '#666666'

# theme
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc set frame_border_active_color '#a89984'
hc set frame_border_normal_color '#282828'
hc set frame_bg_active_color '#a89984'
hc set frame_bg_normal_color '#282828'
hc set frame_border_width 1
hc set show_frame_decorations 'focused_if_multiple'
hc set frame_bg_transparent on
hc set frame_transparent_width 5
hc set frame_gap 4
hc set frame_active_opactiy 1
hc set frame_normal_opacity 0

hc attr theme.title_height 0 ##15
hc attr theme.title_when never
hc attr theme.title_font 'Noto Sans CJK TC:pixelsize=12'
# hc attr theme.title_font 'Dejavu Sans:pixelsize=12' # example using Xft
# hc attr theme.title_font '-*-fixed-medium-r-*-*-13-*-*-*-*-*-*-*'
hc attr theme.title_depth 2 # space below the title's baseline
hc attr theme.active.color '#a89984'
hc attr theme.title_color '#ebdbb2'
hc attr theme.normal.color '#282828'
hc attr theme.urgent.color '#98971a'
hc attr theme.tab_color '#1F1F1Fdd'
hc attr theme.active.tab_color '#2B4F0Add'
hc attr theme.active.tab_outer_color '#6C8257dd'
hc attr theme.active.tab_title_color '#ababab'
hc attr theme.normal.title_color '#928374'
hc attr theme.inner_width 1
hc attr theme.inner_color black
hc attr theme.border_width 3
hc attr theme.floating.border_width 4
hc attr theme.floating.outer_width 1
hc attr theme.floating.outer_color black
hc attr theme.active.inner_color '#a89984'
hc attr theme.urgent.inner_color '#98971a'
hc attr theme.normal.inner_color '#282828'
# copy inner color to outer_color
for state in active urgent normal; do
    hc substitute C theme.${state}.inner_color \
        attr theme.${state}.outer_color C
done
hc attr theme.tiling.outer_width 1
hc attr theme.background_color '#666666'

hc set window_gap 8
hc set frame_padding 0
hc set smart_window_surroundings off
hc set smart_frame_surroundings on
hc set mouse_recenter_gap 0
