#!/usr/bin/env bash

# this is a simple config for herbstluftwm

hc() {
    herbstclient "$@"
}

hc emit_hook reload

######################################################################
#                              Daemons                               #
######################################################################
udiskie &                       # Mounts USB drives
nm-applet &                     # Network Manager
picom --experimental-backends & # UI modifier
./panel.sh
# batticon() {
#     batt="$(pidof cbatticon)"
#     if [[ "$batt" < 1 ]]; then
#         cbatticon -i notification /sys/class/power_supply/BAT0 &
#     else
#         pkill cbatticon
#         cbatticon -i notification /sys/class/power_supply/BAT0 &
#     fi
# }
# volicon() {
#     vol="$(pidof pa-applet)"
#     if [[ "$vol" < 1 ]]; then
#         pa-applet &
#     else
#         pkill pa-applet
#         pa-applet &
#     fi
# }
# volicon
# batticon

######################################################################
#                              Keybinds                              #
######################################################################
source "$HOME/.config/herbstluftwm/keybinds"

######################################################################
#                               Themes                               #
######################################################################
source "$HOME/.config/herbstluftwm/HLWM_themes/theme"

######################################################################
#                              winRules                              #
######################################################################
source "$HOME/.config/herbstluftwm/winRules"

######################################################################
#                           Find the panel                           #
######################################################################
panel=~/.config/herbstluftwm/panel.sh
[ -x "$panel" ] || panel=/etc/xdg/herbstluftwm/panel.sh
for monitor in $(hc list_monitors | cut -d: -f1); do
    # start it on each monitor
    "$panel" "$monitor" &
done
# hc split vertical 0.6
# hc remove
