#!/usr/bin/env bash

# this is a simple config for herbstluftwm

hc() {
    herbstclient "$@"
}

hc emit_hook reload

######################################################################
#                              Daemons                               #
######################################################################
source "$HOME/.config/herbstluftwm/daemons"

######################################################################
#                              Keybinds                              #
######################################################################
source "$HOME/.config/herbstluftwm/keybinds"

######################################################################
#                               Themes                               #
######################################################################
source "$HOME/.config/herbstluftwm/HLWM_themes/theme"

######################################################################
#                              winRules                              #
######################################################################
source "$HOME/.config/herbstluftwm/winRules"

######################################################################
#                           Find the panel                           #
######################################################################
# panel=~/.config/herbstluftwm/panel.sh
panel=~/.config/polybar/launch.sh & # Polybar
[ -x "$panel" ] || panel=/etc/xdg/herbstluftwm/panel.sh
for monitor in $(hc list_monitors | cut -d: -f1); do
    # start it on each monitor
    "$panel" "$monitor" &
done
hc split vertical 0.6
hc remove
