#!/usr/bin/env bash

# disable buildin monitor when using external monitor
bash ~/.local/bin/toVGAMonitor

udiskie &                          # Mounts USB drives
# nm-applet &                      # Network Manager
dunst &                            # Notification Daemon
picom &                            # UI Modifier
fcitx5 -d &                        # Multi-lang Input
