[tools]
# global tool versions go here
# you can set these with `rtx use -g`
node = "16.16.0"
python = "3.11.5"
ruby = "3.2.2"
go = "1.20.7"
java = "openjdk-21"
rust = "1.71.1"

[settings]
# configure `rtx install` to always keep the downloaded archive
always_keep_download = false        # deleted after install by default
always_keep_install = false         # deleted on failure by default

# configure how frequently (in minutes) to fetch updated plugin repository changes
# this is updated whenever a new runtime is installed
# (note: this isn't currently implemented but there are plans to add it: https://github.com/jdxcode/rtx/issues/128)
plugin_autoupdate_last_check_duration = '1 week' # set to 0 to disable updates

# config files with these prefixes will be trusted by default
trusted_config_paths = [
    '~/Workspaces',
]

verbose = false     # set to true to see full installation output, see `RTX_VERBOSE`
jobs = 4            # number of plugins or runtimes to install in parallel. The default is `4`.

experimental = true # enable experimental features
log_level = 'warn' # log verbosity, see `RTX_LOG_LEVEL`

[plugins]
# specify a custom repo url
# note this will only be used if the plugin does not already exist
rust = 'https://github.com/code-lever/asdf-rust'
perl = 'https://github.com/ouest/asdf-perl'
lua = 'https://github.com/Stratus3D/asdf-lua'
php = 'https://github.com/asdf-community/asdf-php'
